from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import random
from olustur import Ui_Form
baglanti = sqlite3.connect("./sifre.db")
islem = baglanti.cursor()
islem.execute("CREATE TABLE IF NOT EXISTS kayit (kayit TEXT)")
baglanti.commit()
class Ui_SIFREOLUSTURUCU(object):
    def setupUi(self, SIFREOLUSTURUCU):
        SIFREOLUSTURUCU.setObjectName("SIFREOLUSTURUCU")
        SIFREOLUSTURUCU.resize(504, 160)
        SIFREOLUSTURUCU.setStyleSheet("#Form{\n"
"background-color: rgb(26, 164, 255);}")
        self.lineEdit = QtWidgets.QLineEdit(SIFREOLUSTURUCU)
        self.lineEdit.setGeometry(QtCore.QRect(100, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(SIFREOLUSTURUCU)
        self.pushButton.setGeometry(QtCore.QRect(10, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.dort)
        self.pushButton_2 = QtWidgets.QPushButton(SIFREOLUSTURUCU)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.alti)
        self.pushButton_3 = QtWidgets.QPushButton(SIFREOLUSTURUCU)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.sekiz)
        self.label = QtWidgets.QLabel(SIFREOLUSTURUCU)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(SIFREOLUSTURUCU)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.sifrekayit)
        self.pushButton_5 = QtWidgets.QPushButton(SIFREOLUSTURUCU)
        self.pushButton_5.setGeometry(QtCore.QRect(350, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.olustur)
        self.retranslateUi(SIFREOLUSTURUCU)
        QtCore.QMetaObject.connectSlotsByName(SIFREOLUSTURUCU)
        self.karakter = "qwertyuıopğüasdfghjklşizxcvbnmöç123456789!^+%+&^%&)(/(=*"
    def retranslateUi(self, SIFREOLUSTURUCU):
        _translate = QtCore.QCoreApplication.translate
        SIFREOLUSTURUCU.setWindowTitle(_translate("SIFREOLUSTURUCU", "ŞİFRE OLUŞTURUCU"))
        self.lineEdit.setText(_translate("SIFREOLUSTURUCU", ""))
        self.pushButton.setText(_translate("SIFREOLUSTURUCU", "4 Haneli"))
        self.pushButton_2.setText(_translate("SIFREOLUSTURUCU", "6 Haneli"))
        self.pushButton_3.setText(_translate("SIFREOLUSTURUCU", "8 Haneli"))
        self.label.setText(_translate("SIFREOLUSTURUCU", "Şifre :"))
        self.pushButton_4.setText(_translate("SIFREOLUSTURUCU", "ŞİFREYİ KAYDET"))
        self.pushButton_5.setText(_translate("SIFREOLUSTURUCU", "KAYITLI ŞİFRELER"))
    def dort(self):
        rasgelesifre1 = random.choice(self.karakter)
        rasgelesifre2 = random.choice(self.karakter)
        rasgelesifre3 = random.choice(self.karakter)
        rasgelesifre4 = random.choice(self.karakter)
        self.toplam = rasgelesifre1 + rasgelesifre2 + rasgelesifre3 + rasgelesifre4
        self.lineEdit.setText(self.toplam)
    def alti(self):
        rasgelesifre1 = random.choice(self.karakter)
        rasgelesifre2 = random.choice(self.karakter)
        rasgelesifre3 = random.choice(self.karakter)
        rasgelesifre4 = random.choice(self.karakter)
        rasgelesifre5 = random.choice(self.karakter)
        rasgelesifre6 = random.choice(self.karakter)
        self.toplamalti = rasgelesifre1 + rasgelesifre2 + rasgelesifre3 + rasgelesifre4 + rasgelesifre5 +rasgelesifre6
        self.lineEdit.setText(self.toplamalti)
    def sekiz(self):
        rasgelesifre1 = random.choice(self.karakter)
        rasgelesifre2 = random.choice(self.karakter)
        rasgelesifre3 = random.choice(self.karakter)
        rasgelesifre4 = random.choice(self.karakter)
        rasgelesifre5 = random.choice(self.karakter)
        rasgelesifre6 = random.choice(self.karakter)
        rasgelesifre7 = random.choice(self.karakter)
        rasgelesifre8 = random.choice(self.karakter)
        self.toplamasekiz = rasgelesifre1 + rasgelesifre2 + rasgelesifre3 + rasgelesifre4 + rasgelesifre5 +rasgelesifre6 + rasgelesifre7 +rasgelesifre8
        self.lineEdit.setText(self.toplamasekiz)
    def sifrekayit(self):
        self.kayit1 = self.lineEdit.text()
        islem.execute("Insert into kayit Values('{}')".format(self.kayit1))
        baglanti.commit()

    def olustur(self):
        self.pencere1 = QtWidgets.QMainWindow()
        self.ui1 = Ui_Form()
        self.ui1.setupUi(self.pencere1)
        self.pencere1.show()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pencere = QtWidgets.QMainWindow()
    ui = Ui_SIFREOLUSTURUCU()
    ui.setupUi(pencere)
    pencere.show()
    sys.exit(app.exec_())